version: "3.3"

services:
    db:
        container_name: "coe-db"
        image: "mariadb:latest"
        volumes:
            - "./db:/var/lib/mysql"
        ports:
            - "18766:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "wpdb_coe"
            MYSQL_USER: "wp_user"
            MYSQL_PASSWORD: "wp_password"

    phpmyadmin:
        container_name: "coe-phpmyadmin"
        image: "phpmyadmin/phpmyadmin"
        depends_on:
            - "db"
        ports:
            - "8081:80"
        environment:
            PMA_HOST: "db"

    wp:
        container_name: "coe-wp"
        image: "wordpress:latest"
        depends_on:
            - "db"
        ports:
            - "8080:80"
        environment:
            WORDPRESS_DB_HOST: "db:3306"
            WORDPRESS_DB_USER: "wp_user"
            WORDPRESS_DB_PASSWORD: "wp_password"
            WORDPRESS_DB_NAME: "wpdb_coe"
            WORDPRESS_DEBUG: 1
        volumes:
            - "./wp:/var/www/html"
            - "./plugins:/var/www/html/wp-content/plugins"
            - "./themes:/var/www/html/wp-content/themes"

    wp-cli:
        container_name: "coe-wpcli"
        image: "wordpress:cli"
        depends_on:
            - "wp"
            - "db"
        environment:
            - APACHE_RUN_USER="www-data"
            - APACHE_RUN_GROUP="www-data"
        volumes:
            - "./wp:/var/www/html:rw"

volumes:
    coe-db: {}
    coe-wp: {}
